# Generated by Django 5.0 on 2024-01-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_topping_pizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='topping',
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping',
            field=models.ManyToManyField(related_name='pizza', to='polls.topping'),
        ),
    ]
