# Generated by Django 5.0 on 2024-01-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_pizza_topping_pizza_topping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='topping',
            new_name='toppings',
        ),
    ]
